---
- name: Playbook
  hosts: cicd
  vars_files:
    - ./vault.yaml
  tasks:
    - name: main |login to docker
      community.docker.docker_login:
         username: "{{ username }}"
         password: "{{ password }}"
         reauthorize: true
         registry:  docker.io
         
         
