---
- name: Playbook
  hosts: cicd
  vars:
   tag : 137
  vars_files:
    - ./vault.yaml
  tasks:
    - name: main |login to docker
      command: docker login -u "{{ username }} " --password "{{password }}"
      
    - name: main | pull image
      command: docker pull docker.io/migra/jenkins.sxb.koffi-accademy.fr:"{{ tag }}"
      register: pull
      
    - name: main | run images
      command: docker run --name="cicd_{{ tag }}" -d -p 8"{{ tag }}":8081 docker.io/migra/jenkins.sxb.koffi-accademy.fr:"{{ tag }}"
      when: pull.changed
