---
- name: Playbook
  hosts: cicd
  vars:
   tag : 112
  vars_files:
    - ./vault.yaml
  tasks:
    - name: main |login to docker
      command: docker login -u "{{ username }} " --password "{{password }}"
    - name: main | pull image
      command: docker pull docker.io/migra/jenkins.sxb.koffi-accademy.fr:"{{ tag }}"
